version: '2.1'
services:
  db:
    image: redis:6-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend
    env_file:
      - ./.env
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  ttp:
    build: .
    restart: on-failure
    networks:
      - backend
    env_file:
      - ./.env
        #stdin_open: true
        #tty: true
    depends_on:
      db:
        condition: service_healthy
networks:
  backend:
    driver: bridge
